%YAML:1.0

# optimization seettings
runMode: normal
testDataSetName: test_n3_v23

debugMode: 0
# optimizer settings
optimizerType: 2
deltaInitialDogleg: 1e13
initialLambda: 1e3
lowerLambda: 1e-10
upperLambda: 1e50
verbosityLM: "SILENT" # SUMMARY  TRYDELTA SILENT
relativeErrorTolerance: 1e-3
setDiagonalDamping: 1
whether_ls: 0
jacobianScale: 1
whether_IPM: 0
#*************************************************************


# in generating task set
parallelFactor: 0.2
PeriodSetAM: [1, 2, 5, 10, 20, 50,100]
timeScaleFactor: 1e4
maxNode_GenerateTaskSet: 20
#*************************************************************

# used in control
Period_Round_For_Control_Opt: 1
# <-1 means full PA
# >1 means remove all the PA part
# 0.1 probably removes all the PA
Priority_assignment_adjustment_threshold: 0.1
weight_priority_assignment: -1e4
# not used in reality, by default, it is 0.1HyperPeriod
PeriodRoundQuantum: 1e3
relativeErrorToleranceInit: 1e-3
relativeErrorToleranceMin: 1e-3
relErrorTolIPM: 1e-5
controlPath: "N5/Case0"
MaxLoopControl: 1e4
weightSchedulability: 500 # actual parameter that controls schedulability constraints' weight, larger means more important 
weightSchedulabilityMax: 1e12
weightSchedulabilityStep: 1.5
weightSchedulabilityMin: 1e12
disturb_init: 1e2
disturb_step: 1.5
disturb_max: 1e5
relativeErrorToleranceOuterLoop: 1e-7
weightHardConstraint: 1e10 # weight of period limits and r<d (3 factors)
#*************************************************************

# used in Nasri19ECRTS 
Job_Limit_Scheduling: 4e4
Nasri19Param_timeout: 1e2
Nasri19Param_max_depth: 0
OverallTimeLimit: 600

# 0 means no, 1 means gradient, 2 means RM only, 3 means objective coefficients only
enableReorder: 0
core_m_dag: 2

# used in SA
randomInitialize: 0
coolingRateSA: 0.99
temperatureSA: 100000
SA_iteration: 10000000
#*************************************************************

# in FindUnsustainable
granularity_FindUnsustainable: 0.01
taskSetSize_FindUnsustainable: 3
#*************************************************************

# no need to adjust
control_sort_obj_coeff_weight: -0.01
control_sort_exec_weight: 1
punishmentFrequency: 10
maxIterationsOptimizer: 1e3
gradientModify: 0
utilTol: 1e-3
linearOptimizerType: "MULTIFRONTAL_CHOLESKY"
weightEnergy: 1e9
LLCompareWithGeneralizedElimination: 0
deltaOptimizer: 1e-5
readTaskMode: RM
baselineLLCompare: 1
printRTA: 0
printFailureFile: 1
# This is actually a relative parameter compared with weightEnergy
punishmentInBarrier: 1e8
noiseModelSigma: 1e0
#*************************************************************

executionTimeModel: 1 # 1 is normal, 2 is more difficult
elimIte: 0
EnergyMode: 1
batchOptimizeFolder: ControlPerformance_Hybrid_DAG
enableMaxComputationTimeRestrict: 1
MaxComputationTimeRestrict: 2
eliminateTol: 1e0
# Variable Elimination, Used in Energy experiment
eliminateStep: 1.5
adjustEliminateMaxIte: 100 # does not control whether enabling elimination
roundTypeInClamp: "rough"
clampTypeMiddle: "rough"
exactJacobian: 0
#*************************************************************




