%YAML:1.0

runMode: compare
# TODO: v6 elimination check failed
testDataSetName: test_n20_v16
optimizerType: 2 # 1 means dogleg, 2 means LM
deltaOptimizer: 1e-4
eliminateJacobianThreshold: 1e30

executionTimeModel: 1 # 1 is normal, 2 is more difficult
enableIPM: 0
elimIte: 1000
EnergyMode: 1

printFailureFile: 1
printRTA: 0
readTaskMode: RM
batchOptimizeFolder: Control_Zhao20
core_m_dag: 2
baselineLLCompare: 1

enableMaxComputationTimeRestrict: 1
MaxComputationTimeRestrict: 2
eliminateTol: 1e0
eliminateStep: 1.5
adjustEliminateMaxIte: 100


weightLogBarrier: 0
weightDrawBegin: 1e-6
weightDrawEnd: 1e5
roundTypeInClamp: "rough"

# This is actually a relative parameter compared with weightEnergy
punishmentInBarrier: 1e5

noiseModelSigma: 1e0
relativeErrorToleranceInit: 1e-7
relativeErrorTolerance: 1e-7
relativeErrorToleranceMin: 1e-10
relErrorTolIPM: 1e-5
toleranceBarrier: 1e-6

punishmentFrequency: 10

randomInitialize: 0
deltaInitialDogleg: 1e13

initialLambda: 1e2
lowerLambda: 1e-20
upperLambda: 1e20
coolingRateSA: 0.99
temperatureSA: 100000
granularityInBF: 1

SA_iteration: 1000000

controlPath: "N5/Case0"
MaxLoopControl: 1e4
exactJacobian: 0
utilTol: 1e-3
debugMode: 1
verbosityLM: "SUMMARY"
linearOptimizerType: "MULTIFRONTAL_QR"
# all the weight parameters used in control experiment
weightEnergy: 1e9 # used in first formulation only
weightSchedulability: 500 # actual parameter that controls schedulability constraints' weight, larger means more important 
weightSchedulabilityMax: 1e12
weightSchedulabilityStep: 1.5
weightSchedulabilityMin: 1e12
disturb_init: 1e0
disturb_step: 1.5
disturb_max: 4e3
relativeErrorToleranceOuterLoop: 1e-7
LLCompareWithGeneralizedElimination: 1
weightHardConstraint: 1e10 # weight of period limits and r<d (3 factors)
enableReorder: 0