%YAML:1.0

testDataSetName: test_n3_v24

fully_preemptive: 1
deltaOptimizer: 1e-5

minWeightToBegin: 1e8
weightStep: 1e2
eliminateTol: 1e0
eliminateStep: 2
enableIPM: 0
iterationNumIPM_Max: 10
exactJacobian: 0
weightLogBarrier: 0
roundTypeInClamp: "fine"
# If this number is much larger than the other parts(kike, weightEntry), 
# the system may be indetermined in Jacobian

# This is actually a relative parameter compared with weightEnergy
punishmentInBarrier: 1e5

noiseModelSigma: 1e-3
relativeErrorTolerance: 1e-5
relErrorTolIPM: 1e-6
xTolIPM: 1e-3
toleranceBarrier: 1e-6



punishmentFrequency: 10

optimizerType: 1 # 1 means dogleg, 2 means LM

deltaInitialDogleg: 1e1

initialLambda: 1e15
lowerLambda: 1e-5
upperLambda: 1e30


granularityInBF:10
readTaskMode: RM
eliminateVariableThreshold: 1.0

debugMode: 1










# something not used 
weightEnergyMinOrder: -10
weightEnergyMaxOrder: 1
weightEnergy: 1e8
RTA_TYPE: "WAP"

