%YAML:1.0

runMode: compare
# TODO: v6 elimination check failed
testDataSetName: test_n10_v8
optimizerType: 2 # 1 means dogleg, 2 means LM
deltaOptimizer: 1e-5
debugMode: 1
executionTimeModel: 1 # 1 is normal, 2 is more difficult
enableIPM: 0
elimIte: 1000
EnergyMode: 1
exactJacobian: 0
printFailureFile: 0
printRTA: 1
readTaskMode: RM
batchOptimizeFolder: MIGP
core_m_dag: 2
baselineLLCompare: 2

enableMaxComputationTimeRestrict: 1
MaxComputationTimeRestrict: 2
eliminateTol: 1e-1
eliminateStep: 3
adjustEliminateMaxIte: 10


weightLogBarrier: 0
weightDrawBegin: 1e-6
weightDrawEnd: 1e5
roundTypeInClamp: "fine"

# This is actually a relative parameter compared with weightEnergy
punishmentInBarrier: 1e5

noiseModelSigma: 1e0
relativeErrorTolerance: 1e-7
relErrorTolIPM: 1e-5
toleranceBarrier: 1e-6

punishmentFrequency: 10

randomInitialize: 0
deltaInitialDogleg: 1e10

initialLambda: 1e0
lowerLambda: 1e-20
upperLambda: 1e30
coolingRateSA: 0.99
temperatureSA: 100000
granularityInBF: 1

SA_iteration: 1000000

utilTol: 0.001

weightEnergy: 1e4
