%YAML:1.0

testDataSetName: test_n10_v4

deltaOptimizer: 1e-2
weightEnergyMinOrder: -10
weightEnergyMaxOrder: 1
weightEnergy: 1e10
# If this number is much larger than the other parts(kike, weightEntry), 
# the system may be indetermined in Jacobian

# This is actually a relative parameter compared with weightEnergy
punishmentInBarrier: 1e9

noiseModelSigma: 1e-3
relativeErrorTolerance: 1e-3
toleranceBarrier: 1e-6
eliminateTol: 1e1


punishmentFrequency: 10
weightLogBarrier: 1
optimizerType: 1 # 1 means dogleg, 2 means LM

deltaInitialDogleg: 1e1

initialLambda: 1e1
lowerLambda: 1e-5
upperLambda: 1e30


granularityInBF:1
readTaskMode: RM
eliminateVariableThreshold: 1.0

debugMode: 1

