%YAML:1.0

runMode: normal

testDataSetName: test_n10_v6
optimizerType: 1 # 1 means dogleg, 2 means LM
deltaOptimizer: 1e-5
debugMode: 1
executionTimeModel: 2 # 1 is normal, 2 is more difficult
enableIPM: 0
elimIte: 000
EnergyMode: 2
exactJacobian: 0
printFailureFile: 0
readTaskMode: RM

enableMaxComputationTimeRestrict: 1
MaxComputationTimeRestrict: 3
weightStep: 1e2
eliminateTol: 1e-1
eliminateGranularity: 1e-1
eliminateStep: 4
adjustEliminateMaxIte: 20


weightLogBarrier: 0
weightDrawBegin: 1e-6
weightDrawEnd: 1e5
roundTypeInClamp: "none"

# This is actually a relative parameter compared with weightEnergy
punishmentInBarrier: 1e5

noiseModelSigma: 1e0
relativeErrorTolerance: 1e-5
relErrorTolIPM: 1e-5
xTolIPM: 1e-3
toleranceBarrier: 1e-6

computationBound: 2.0
punishmentFrequency: 10

randomInitialize: 0
deltaInitialDogleg: 1e10

initialLambda: 1e5
lowerLambda: 1e-20
upperLambda: 1e30
coolingRateSA: 0.99
temperatureSA: 100000
granularityInBF: 1

eliminateVariableThreshold: 1.0
SA_iteration: 1000000

utilTol: 0.001

weightEnergy: 1e8

