%YAML:1.0

testDataSetName: test_n10_v2

deltaOptimizer: 1e-6
weightEnergyMinOrder: -10
weightEnergyMaxOrder: 1
weightEnergy: 1e20
minWeightToBegin: 1e3
weightStep: 1e2
eliminateTol: 10
eliminateStep: 100000

# If this number is much larger than the other parts(kike, weightEntry), 
# the system may be indetermined in Jacobian

# This is actually a relative parameter compared with weightEnergy
punishmentInBarrier: 1e5

noiseModelSigma: 1e-3
relativeErrorTolerance: 1e-8
convergTolInterior: 1e-8
toleranceBarrier: 1e-6



punishmentFrequency: 10
weightLogBarrier: 1
optimizerType: 1 # 1 means dogleg, 2 means LM

deltaInitialDogleg: 1e1

initialLambda: 1e1
lowerLambda: 1e-5
upperLambda: 1e30


granularityInBF:1
readTaskMode: RM
eliminateVariableThreshold: 1.0

debugMode: 1

