%YAML:1.0

runMode: normal
# TODO: v6 elimination check failed
testDataSetName: test_n3_v9
optimizerType: 2
deltaOptimizer: 1e-4
eliminateJacobianThreshold: 1e30

executionTimeModel: 2 # 1 is normal, 2 is more difficult
enableIPM: 0
elimIte: 100
EnergyMode: 2

printFailureFile: 1
printRTA: 0
readTaskMode: RM
batchOptimizeFolder: DAGPerformance
core_m_dag: 16
baselineLLCompare: 1

enableMaxComputationTimeRestrict: 1
MaxComputationTimeRestrict: 2
eliminateTol: 1e1
eliminateStep: 10
adjustEliminateMaxIte: 10

weightLogBarrier: 0
weightDrawBegin: 1e-6
weightDrawEnd: 1e5
roundTypeInClamp: "none"
clampTypeMiddle: "none"

# This is actually a relative parameter compared with weightEnergy
punishmentInBarrier: 1e8

noiseModelSigma: 1e0
relativeErrorToleranceInit: 1e-3
relativeErrorTolerance: 1e-3
relativeErrorToleranceMin: 1e-3
relErrorTolIPM: 1e-5
toleranceBarrier: 1e-6


punishmentFrequency: 10

randomInitialize: 0
deltaInitialDogleg: 1e13

initialLambda: 1e4
lowerLambda: 1e-10
upperLambda: 1e20
coolingRateSA: 0.99
temperatureSA: 100000
granularityInBF: 1

SA_iteration: 1000000

granularity_FindUnsustainable: 0.01
taskSetSize_FindUnsustainable: 3
maxIterationsOptimizer: 1e3
gradientModify: 0
controlPath: "N5/Case0"
MaxLoopControl: 1e4
exactJacobian: 0
utilTol: 1e-3
debugMode: 0
verbosityLM: "SUMMARY"
linearOptimizerType: "MULTIFRONTAL_CHOLESKY"
# all the weight parameters used in control experiment
weightEnergy: 1e9 # used in first formulation only
weightSchedulability: 500 # actual parameter that controls schedulability constraints' weight, larger means more important 
weightSchedulabilityMax: 1e12
weightSchedulabilityStep: 1.5
weightSchedulabilityMin: 1e12
disturb_init: 1e0
disturb_step: 1.5
disturb_max: 1e3
relativeErrorToleranceOuterLoop: 1e-7
LLCompareWithGeneralizedElimination: 0
weightHardConstraint: 1e10 # weight of period limits and r<d (3 factors)
enableReorder: 0

maxNode_GenerateTaskSet: 20
parallelFactor: 0.2
PeriodSetAM: [1,2,5,10,20,50,200,1000]
timeScaleFactor: 1e4
whetherWriteNarsiTaskSet: 0
SpeedOptimizeOption: 1
SkipRateFindElimination: 0.0
