%YAML:1.0

runMode: normal
# TODO: v6 elimination check failed
testDataSetName: test_n10_v8
optimizerType: 1 # 1 means dogleg, 2 means LM
deltaOptimizer: 1e-5
debugMode: 0
executionTimeModel: 1 # 1 is normal, 2 is more difficult
enableIPM: 0
elimIte: 1000
EnergyMode: 2
exactJacobian: 0
printFailureFile: 0
readTaskMode: RM
batchCompareFolder: elimination

enableMaxComputationTimeRestrict: 1
MaxComputationTimeRestrict: 2
weightStep: 1e2
eliminateTol: 1e-1
eliminateStep: 4
adjustEliminateMaxIte: 10


weightLogBarrier: 0
weightDrawBegin: 1e-6
weightDrawEnd: 1e5
roundTypeInClamp: "fine"

# This is actually a relative parameter compared with weightEnergy
punishmentInBarrier: 1e5

noiseModelSigma: 1e0
relativeErrorTolerance: 1e-7
relErrorTolIPM: 1e-5
xTolIPM: 1e-3
toleranceBarrier: 1e-6

computationBound: 2.0
punishmentFrequency: 10

randomInitialize: 0
deltaInitialDogleg: 1e10

initialLambda: 1e-1
lowerLambda: 1e-20
upperLambda: 1e30
coolingRateSA: 0.99
temperatureSA: 100000
granularityInBF: 1

eliminateVariableThreshold: 1.0
SA_iteration: 1000000

utilTol: 0.001

weightEnergy: 1e8
